# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine

WORKDIR /app

# Install dependencies and build
COPY package.json package-lock.json tsconfig.json ./
COPY server.ts setup.js install.js mcp.json test-custom-fields.js .

RUN npm install --ignore-scripts && npm run build

# Copy remaining files
COPY . .

# Default command
CMD ["node", "dist/server.js"]
